webapp/app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classify_app.urls'))
]

webapp/classify_app/urls.py
from django.urls import path
from . import views

app_name='classify_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

webapp/classify_app/models.py
from django.db import models

import re
import sys
import math
import nagisa
import numpy as np
import urllib.request
from bs4 import BeautifulSoup

# ナイーブベイズ分類器
class NaiveBayes:
  def in_category(self, word, category):
    if word in self.word_ct[category]:
        return float(self.word_ct[category][word])# カテゴリー内の単語出現回数
    return 0.0
    
  def word_prob(self, word, category):
    # カテゴリ内の対象単語の出現率
    # 単語のカテゴリー内出現回数 + 1 / カテゴリー内単語数 + 学習データの全単語数 (加算スムージング)
    prob = (self.in_category(word, category) + 1.0) / (sum(self.word_ct[category].values())+ len(self.vocabularies) * 1.0)
    return prob
        
  def score(self, words, category):
    # カテゴリー出現率P(C)を取得 (アンダーフロー対策で対数をとった後で加算)
    score = math.log(float(self.category_ct[category] / sum(self.category_ct.values())))
      
    # カテゴリー内の単語出現率を文書内のすべての単語で求める
    for word in words:
        # カテゴリー内の単語出現率P(Wn|C)を計算 (アンダーフロー対策で対数をとった後で加算)
        score += math.log(self.word_prob(word, category))
    return score
    
  def classify(self,link):
    # 対象記事の形態素解析
    html = urllib.request.urlopen(link)
    soup = BeautifulSoup(html, 'html.parser')

    text = soup.find_all("p")
    text = [t.text for t in text]
    text = ','.join(text)

    words = nagisa.tagging(text)
    words = nagisa.filter(text, filter_postags=['助詞', '助動詞','接頭辞','接尾辞','補助記号','URL','空白']).words
    words = list(filter(lambda x: len(x) != 1, words)) # 一文字の単語を削除
    words = list(filter(lambda x: x != '', [re.sub(r'[0-9]', "", s) for s in words]))# 数字を削除

    # 学習データをloadする
    self.word_ct = np.load('./classify_app/data/word_ct.npy',allow_pickle=True).tolist()
    self.category_ct = np.load('./classify_app/data/category_ct.npy',allow_pickle=True).tolist()
    self.vocabularies = np.load('./classify_app/data/vocabularies.npy',allow_pickle=True).tolist()

    best_category = None # もっとも近いカテゴリ

    max_prob = -sys.maxsize# 最小整数値を設定

    # カテゴリ毎に対象文書（単語）のカテゴリー出現率P(C|W)を求める
    for category in self.category_ct.keys():
      # 文書内のカテゴリー出現率P(C|W)を求める
      prob = self.score(words, category)
      if prob > max_prob:
        max_prob = prob
        best_category = category

    return best_category

webapp/classify_app/forms.py
from django import forms

class UrlForm(forms.Form):
  url = forms.URLField(label='推定する記事のURL')

webapp/classify_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import UrlForm
from .models import NaiveBayes

import re

def index(request):
    template = loader.get_template('classify_app/index.html')
    context = {'form': UrlForm()}
    return HttpResponse(template.render(context, request))

def predict(request):
    if not request.method == 'POST':
        return
        redirect('classify_app:index')
    
    form = UrlForm(request.POST)
    
    if not form.is_valid():
        raise ValueError('Formが不正です')

    pattern = "https?://[\w/:%#\$&\?\(\)~\.=\+\-]+"
    link = re.findall(pattern, str(form))

    target = NaiveBayes()
    category = target.classify(link[0])

    template = loader.get_template('classify_app/result.html')
    
    context = {
        'url':form,
        'category':category
        }
    
    return HttpResponse(template.render(context, request))
    

webapp/classify_app/templates/classify_app/base.html
<!DOCTYPE html>
<html lang='ja'>
<head>
  <meta charset='UTF-8'>
  {% load static %}
  {% load bootstrap4 %}
  {% bootstrap_css %}
  <link rel='stylesheet' type='text/css' href="{% static 'classify_app/css/style.css' %}">
  {% bootstrap_javascript jquery='full' %}
  <title>記事カテゴリ判定 | {% block title %}{% endblock %}</title>
</head>
<head>
  <nav class='navbar navbar-expand-lg navbar-light bg-light'>
    <a class='navbar-brand' href='#'>記事カテゴリ判定AIアプリ</a>
  </nav>
  <div class='container'>
    {% block content %}{% endblock %}
  </div>
</head>

</html>

webapp/classify_app/templates/classify_app/index.html
{% extends 'classify_app/base.html' %}
{% block title %}記事カテゴリ推定アプリメニュー{% endblock %}

{% block content %}
<div>
  <h4 class='mt-4 mb-5 border-bottom'>記事カテゴリを推定しよう！</h4>
  <p>記事のURLを入力してください</p>
  <form action="{% url 'classify_app:predict' %}" method="post" class="form" enctype="multipart/form-data">
    <!-- 外部サイトからの攻撃を防ぐ -->
    {% csrf_token %}
    <div class="form-group">
      {{ form.url }}
    </div>
    <button type="submit" class="btn btn-primary">推定する！</button>
  </form>
</div>
{% endblock %}

webapp/classify_app/templates/classify_app/result.html
{% extends 'classify_app/base.html' %}
{% block title %}記事カテゴリ推定結果{% endblock %}

{% block content %}
<div>
  <h4 class="mt-4 mb-5 border-bottom">記事カテゴリ推定結果はこちら</h4>

  <table class='table'>
    <tbody>
      <tr>{{ url }}</tr>
      <tr>
        <td>推定カテゴリ</td>
        <td>{{ category }}</td>
    </tbody>
  </table>

  <a href="{% url 'classify_app:index' %}" class='btn btn-primary'>前のページに戻る</a>

</div>
{% endblock %}